author = 'Oxalin'
country_code = 'GB'
description = "Snow Hill Lines from Rowley Regis to Kidderminster, and the Stourbridge Branch Line"
display_name = 'Stourbridge'
doc_files = [ 'Stourbridge.md' ]
factual = true
img_files = [ 'Stourbridge.bmp' ]
name = 'Stourbridge'
release_date = '2026-07-07'
rly_file = 'Stourbridge.rly'
ssn_files = [ ]
ttb_files = [ 'Stourbridge_2026-03-11' ]
year = 2026
signal_position - "left"
version = '1.0.0'
